# Generated by Django 4.1.1 on 2022-10-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_comment_author_alter_comment_post'),
        ('blog', '0013_alter_comment_post'),
    ]

    operations = [
    ]
